swagger: '2.0'
info:
  title: consultation.gouv.fr
  description: Catalogue des outils de consultation
  version: 0.1.0
basePath: /outil/v1
produces:
  - application/json
paths:
  /outil.json:
    get:
      summary: Récupérer la liste des API listées sur api.gouv.fr
      responses:
        '200':
          description: La liste des API
          schema:
            type: array
            items:
              $ref: "#/definitions/outil"

definitions:
  api:
    type: object
    properties:
      title:
        type: string
      url:
        type: string
      description:
        type: string
      image:
        type: string
      domain:
        type: string
      owner:
        type: string
      contract:
        type: string
      keywords:
        type: array
        items:
          type: string
      clients:
        type: array
        items:
          type: string
      partners:
        type: array
        items:
          type: string
