version: 2

jobs:
  build:
    working_directory: ~/consultation-gouv/consultation.gouv.fr
    parallelism: 1
    shell: /bin/bash --login
    environment:
      NOKOGIRI_USE_SYSTEM_LIBRARIES: true
    docker:
      - image: circleci/ruby:2.3
    steps:
      - checkout
      - run: bundle install
      - run: bundle exec jekyll --version
      # below are the tests
      - run: bundle exec jekyll doctor
      - run: bundle exec jekyll build
      - run: grep "css/main.css" _site/index.html

workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: [pprod, production]

